TEST_NAMES += mutate_copy
TEST_NAMES += point_mutate
TEST_NAMES += sequence_mutate_copy
TEST_NAMES += transpose_invert_mutate

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
