TEST_NAMES += CappedOutputIterator
TEST_NAMES += CappedSet
TEST_NAMES += do_random_walk_approximation
TEST_NAMES += do_random_walk_exact
TEST_NAMES += do_random_walk_indexmap_approximation
TEST_NAMES += do_random_walk_normal_approximation
TEST_NAMES += EmptyType
TEST_NAMES += MemoizeCtor

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
