TARGET_NAMES += algorithm
TARGET_NAMES += hardware
TARGET_NAMES += library
TARGET_NAMES += mutate
TARGET_NAMES += operations
TARGET_NAMES += program
TARGET_NAMES += spec
TARGET_NAMES += utility

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateForwarding
