TEST_NAMES += RandomBool
TEST_NAMES += Decrement
TEST_NAMES += Generate
TEST_NAMES += Increment
TEST_NAMES += Negate
TEST_NAMES += Not
TEST_NAMES += Terminal

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
