TEST_NAMES += InstRangeCopier_Default
TEST_NAMES += InstRangeCopier_Indel
TEST_NAMES += InstRangeCopier_Perfect
TEST_NAMES += StarterConfig

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
