TEST_NAMES += InstRangeCopier_Default
TEST_NAMES += InstRangeCopier_Indel
TEST_NAMES += InstRangeCopier_Perfect
TEST_NAMES += StarterConfig
TEST_NAMES += TransposeWindowDisplacementGenerator_Default
TEST_NAMES += TransposeWindowDisplacementGenerator_Pareto
TEST_NAMES += TransposeWindowSizeGenerator_Default
TEST_NAMES += TransposeWindowSizeGenerator_Pareto

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
