TARGET_NAMES += hello-world
TARGET_NAMES += identity
TARGET_NAMES += changing-enviroment
TARGET_NAMES += contextual-signal

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateForwarding
