TARGET_NAMES += evolve
TARGET_NAMES += identity
TARGET_NAMES += changing-enviroment
TARGET_NAMES += signal-counting

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateForwarding

