TEST_NAMES += Add
TEST_NAMES += Decrement
TEST_NAMES += Increment
TEST_NAMES += Not
TEST_NAMES += Subtract

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
