TEST_NAMES += Add
TEST_NAMES += AnchorGlobal
TEST_NAMES += AnchorLocal
TEST_NAMES += Decrement
TEST_NAMES += Increment
TEST_NAMES += Not
TEST_NAMES += Nop
TEST_NAMES += Subtract
TEST_NAMES += Terminate

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
