TEST_NAMES += BitwiseAnd
TEST_NAMES += BitwiseNot
TEST_NAMES += BitwiseOr
TEST_NAMES += BitwiseShift
TEST_NAMES += BitwiseXor
TEST_NAMES += CountOnes
TEST_NAMES += RandomFill

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
