TEST_NAMES += drag_to
TEST_NAMES += execute_core
TEST_NAMES += execute_cpu
TEST_NAMES += inst_indel_copy
TEST_NAMES += module_indel_copy
TEST_NAMES += mutate_bits
TEST_NAMES += mutate_bytes
TEST_NAMES += slide_n
TEST_NAMES += sloppy_copy

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
