TEST_NAMES += advance_core
TEST_NAMES += drag_to
TEST_NAMES += execute_core
TEST_NAMES += execute_core_cycles
TEST_NAMES += execute_core_slice
TEST_NAMES += execute_cpu
TEST_NAMES += execute_cpu_n_cycles
TEST_NAMES += execute_cpu_n_slices
TEST_NAMES += inst_indel_copy
TEST_NAMES += module_indel_copy
TEST_NAMES += mutate_bits
TEST_NAMES += mutate_bytes
TEST_NAMES += next
TEST_NAMES += prev
TEST_NAMES += slide_n
TEST_NAMES += slide_to
TEST_NAMES += sloppy_copy
TEST_NAMES += transpose_window

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
