#pragma once
#ifndef SGPL_OPERATIONS_COMPARISON_COMPARISON_HPP_INCLUDE
#define SGPL_OPERATIONS_COMPARISON_COMPARISON_HPP_INCLUDE

#include "Equal.hpp"
#include "GreaterThan.hpp"
#include "LessThan.hpp"

#endif // #ifndef SGPL_OPERATIONS_COMPARISON_COMPARISON_HPP_INCLUDE
